#build
FROM node:24-alpine3.22 AS builder

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN --mount=type=cache,target=/root/.npm \
npm ci

COPY frontend/ .

RUN npm run build

#runtime
FROM nginx:1.31-alpine

COPY nginx/nginx.conf /etc/nginx/nginx.conf

COPY --from=builder \
    --chown=nginx:nginx \
    /app/dist \
    /usr/share/nginx/html

RUN chown -R nginx:nginx \
    /var/cache/nginx \
    /var/run

USER nginx

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]